// Assembles data.js from tools/terrain-data.json (points/lines/schedule, generated by
// gen-terrain-data.mjs) plus the hand-authored meta/factions/storyboard/notes below.
import fs from 'fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const P = (...a) => resolve(root, ...a);

const d = JSON.parse(fs.readFileSync(P('tools/terrain-data.json'), 'utf8'));
const pointsJson = JSON.stringify(d.points);
const linesJson = JSON.stringify(d.lines);   // route/branch fields kept (extra, engine-ignored) — used by the live-trains extension to map schedule trips to the right curve
const scheduleJson = JSON.stringify(d.schedule);

const HEADER = `/* =====================================================================
 *  data.js — SF Bay Area 3D · BART + Caltrain, real terrain
 *  ---------------------------------------------------------------------
 *  A fork of keithligh/cinematic-3d-battle-engine (MIT), same engine as
 *  hk-mtr-3d v2 (via hk-mtr-3d's own copy, which forked poly2019's
 *  generalized fork). The engine modules are unedited except the same two
 *  small extensions hk-mtr-3d v2 made (open-year label gating, fade-IN
 *  lines) — inert here since this build doesn't use the year axis, plus
 *  ONE new addition specific to this fork: real-schedule-driven trains
 *  (entities.js buildLiveTrains()/updateLiveTrains()) and a click-to-see-
 *  next-arrivals popup, both driven by window.BATTLE_DATA.schedule below
 *  (NOT part of the engine's own data contract — a fork-only extension,
 *  harmless to the validator, which only checks for known required keys).
 *
 *  This is a live interactive map, not a scripted documentary: the
 *  storyboard is a single long-hold establishing shot, so the Director
 *  settles there and the user free-orbits from the start (dragging always
 *  pauses the Director, an existing engine behaviour).
 * ===================================================================== */
window.BATTLE_DATA = (function () {

  const LINE_FAC = {
    yel: ["Yellow Line", "#FFFF33"], org: ["Orange Line", "#FF9933"], grn: ["Green Line", "#339933"],
    red: ["Red Line", "#FF0000"], blu: ["Blue Line", "#0099CC"], gry: ["Grey Line (OAK)", "#B0BEC7"],
    ct: ["Caltrain", "#CE202F"],
  };
  const shade = (hex, f) => { const n = parseInt(hex.slice(1), 16), r = n >> 16, g = (n >> 8) & 255, b = n & 255,
    c = (v) => Math.max(0, Math.min(255, Math.round(v + (f > 0 ? (255 - v) * f : v * f))));
    return (c(r) << 16) | (c(g) << 8) | c(b); };
  const factions = {};
  for (const [code, [name, hex]] of Object.entries(LINE_FAC)) {
    const main = parseInt(hex.slice(1), 16);
    factions[code] = { main, glow: shade(hex, 0.35), dim: shade(hex, -0.45), css: hex,
      name_zh: name, name_en: name, role: "neutral", maxStrength: 1, defaultFlag: code };
  }

  const meta = {
    geo: { minLng: -122.55, maxLng: -121.50, minLat: 36.95, maxLat: 38.08, Z: 12 },
    dayMin: 0, dayMax: 1, year: 2026, month: 7, lastDay: 10,
    title: "SF Bay Area 3D", subtitle: "BART + Caltrain, real terrain",
    theme: {
      grade: { filter: "saturate(0.9) contrast(1.02) brightness(1.0)", vignette: 0.2, grain: 0.01 },
      sky: { day: 0x8fa8c0, dayB: 0xc0cfda, night: 0x0d1420, nightB: 0x1b2636 },
    },
  };
  const ui = { sceneLabel: false,
    disclaimer: "Imagery © Esri, Maxar, Earthstar Geographics · elevation SRTM courtesy USGS" };

  const flagLegend = Object.keys(LINE_FAC).map(code => ({ flag: code, zh: LINE_FAC[code][0], en: LINE_FAC[code][0], faction: code }));

  const intro = {
    title_zh: "SF Bay Area 3D", title_en: "SF Bay Area 3D",
    sub_zh: "BART + Caltrain, real terrain and a real weekday schedule.",
    sub_en: "BART + Caltrain, real terrain and a real weekday schedule.",
    cam: { lng: -122.22, lat: 37.72, dist: 2700, az: 20, el: 52, orbit: 0.4 },
  };
  const outro = {
    title_zh: "SF Bay Area 3D", title_en: "SF Bay Area 3D",
    narration_zh: "", narration_en: "",
    cam: { lng: -122.22, lat: 37.72, dist: 2800, az: 40, el: 54, orbit: 0.3, tween: 3 },
  };

  const regions = [
    { name_zh: "San Francisco", name_en: "San Francisco", lng: -122.44, lat: 37.77, h: 0 },
    { name_zh: "Oakland", name_en: "Oakland", lng: -122.27, lat: 37.80, h: 0 },
    { name_zh: "San Jose", name_en: "San Jose", lng: -121.89, lat: 37.34, h: 0 },
  ];
${pointsJson.replace(/^\[/, '  const points = [').replace(/\]$/, '];')}
${linesJson.replace(/^\[/, '  const lines = [').replace(/\]$/, '];')}
  const geography = { regions, points, lines };

  const units = [];
  const arrows = [];
  const hotspots = [];
  const weather = [ { d: 0, night: 0.08, fog: 0.05, rain: 0, smoke: 0, zh: "晴", en: "Clear" } ];

  // one long-hold establishing shot — the Director parks here; free-look from the start
  const storyboard = [
    { day: 0, hold: 1e6,
      cam: { lng: -122.22, lat: 37.72, dist: 2700, az: 20, el: 52, orbit: 0.15 },
      dateLabel: "今日 · Live", title_zh: "SF Bay Area 3D", title_en: "SF Bay Area 3D",
      narration_zh: "拖曳自由環視 · 點擊車站查看下班車 · BART與Caltrain真實路線與時刻表。",
      narration_en: "Drag to free-look · click a station for its next departures · real BART + Caltrain routes and schedule.",
      focus: [] },
  ];

  const notes = {
    summary: "SF Bay Area 3D — an interactive 3D map of BART and Caltrain over real terrain, with trains positioned by the real published weekday GTFS schedule. · SF Bay Area 3D — 一幅疊映於真實地形之上的BART與Caltrain互動立體地圖，列車位置依真實公開的平日GTFS時刻表驅動。",
    caveats: [
      "地形起伏依真實SRTM高程自動推算；地下深度為已知隧道走廊的近似估算（GTFS本身不含隧道/橋樑標籤），Caltrain目前無隧道故一律視為地面。 · Relief is auto-derived from real SRTM elevation; underground depth is an approximation of known tunnel corridors (GTFS carries no tunnel/bridge tag) — Caltrain has no tunnels today, so it's rendered flat.",
      "列車位置取自單一代表性平日時刻表（BART核心平日班次、Caltrain service_id 72982），非即時GPS位置。 · Train positions come from one representative weekday's real schedule (BART's core weekday service, Caltrain service_id 72982), not live GPS.",
      "路綫幾何為GTFS shapes.txt簡化後之近似，並以「貪婪覆蓋」演算法處理分支，非測量級精度。 · Route geometry is simplified GTFS shapes.txt, branches reconstructed via a greedy-coverage heuristic — approximate, not survey-grade.",
    ],
    sources: "路綫、車站與時刻表資料來自BART官方GTFS（bart.gov）與Caltrain GTFS（經511.org）。地形：AWS Terrarium DEM（SRTM/USGS）；影像：Esri World Imagery（© Esri, Maxar, Earthstar Geographics）。 · Route, station, and schedule data from BART's official GTFS (bart.gov) and Caltrain's GTFS (via 511.org). Elevation: AWS Terrarium DEM (SRTM/USGS). Imagery: Esri World Imagery (© Esri, Maxar, Earthstar Geographics).",
  };

${scheduleJson.replace(/^\[/, '  const scheduleRaw = [').replace(/\]$/, '];')}

  return { meta, ui, factions, intro, outro, flagLegend, geography, units, arrows,
           hotspots, weather, storyboard, notes, schedule: scheduleRaw };
})();
`;

fs.writeFileSync(P('data.js'), HEADER);
console.log('data.js: ' + (fs.statSync(P('data.js')).size / 1024).toFixed(0) + ' KB');
